name: Publish

on:
  workflow_dispatch:
  
permissions:
  contents: write
  
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    
    - name: 下载最新正式版 AriaNg
      uses: robinraju/release-downloader@v1.7
      id: download
      with:
        # 源存储库的路径
        # 预期格式 {owner}/{repo}
        # 默认值: ${{ github.repository }}
        repository: "mayswind/AriaNg"
        # 将下载目标设置为最新版本的标志
        # 默认值是 'false'
        latest: true
        # 要下载的文件的名称
        # 使用此字段仅用于指定除tarball或zipball以外的文件名，如果有的话
        # 支持通配符模式 (例如: '*', '*.deb', '*.zip' 等等..)
        fileName: "AriaNg-*.zip"
        # 在 $GITHUB_WORKSPACE 下放置下载文件的相对路径
        # 如果不存在，它将自动创建目标目录
        # 例如: out-file-path: "my-downloads" => 它将创建目录 $GITHUB_WORKSPACE/my-downloads
        out-file-path: "downloads"
      
    - name: 解压 AriaNg-*.zip 文件
      run: |
        mkdir -p "gh-pages/"
        unzip -o "./downloads/AriaNg-${{steps.download.outputs.tag_name}}.zip" -d "./gh-pages/"
        echo "${{ vars.CNAME }}" > "./gh-pages/CNAME"  # 绑定自定义域名

    - name: 部署到 GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./gh-pages
        publish_branch: gh-pages
        commit_message: 'AriaNg v${{steps.download.outputs.tag_name}} 更新'
